import React from "react";
const money = (value) => `$${Math.round(Number(value || 0)).toLocaleString("es-CL")}`;
const lineTotal = (item) => Number.isFinite(item.totalLinea)
  ? item.totalLinea
  : Math.round(Number(item.cantidad || 0) * Number(item.costoUnitario || 0)) -
    Math.round((Number(item.cantidad || 0) * Number(item.costoUnitario || 0) * Number(item.descuentoPct || 0)) / 100);
export default function PurchasePrintView({company, purchase}) {
  return <article className="po-print"><header><div><small>COMPRA</small><h1>{purchase.numero || "Compra por asignar"}</h1><p>{purchase.ordenCompraNumero ? `Originada desde ${purchase.ordenCompraNumero}` : "Compra directa"}</p></div><strong>{purchase.estado || "borrador"}</strong></header><div className="po-print__parties"><section><small>Empresa</small><strong>{company?.nombreComercial || company?.razonSocial || "Empresa"}</strong><p>{company?.rut || ""}</p></section><section><small>Proveedor</small><strong>{purchase.proveedorSnapshot?.razonSocial || "—"}</strong><p>{purchase.proveedorSnapshot?.rut || ""}</p></section><section><small>Documento</small><strong>{purchase.tipoDocumento || "sin documento"}</strong><p>{purchase.numeroDocumentoProveedor || "Sin número"}</p><p>{purchase.fechaCompra || "—"}</p></section></div><table><thead><tr><th>Ítem</th><th>Cantidad</th><th>Costo</th><th>Desc.</th><th>Total</th></tr></thead><tbody>{purchase.items?.map((item) => <tr key={item.lineaId}><td><strong>{item.nombre}</strong><small>{item.codigo}</small></td><td>{item.cantidad}</td><td>{money(item.costoUnitario)}</td><td>{item.descuentoPct}%</td><td>{money(lineTotal(item))}</td></tr>)}</tbody></table><div className="po-print__totals"><div><span>Neto</span><strong>{money(purchase.neto)}</strong></div><div><span>IVA</span><strong>{money(purchase.iva)}</strong></div><div><span>Total</span><strong>{money(purchase.total)}</strong></div></div>{purchase.condicionesPago && <section><strong>Condiciones</strong><p>{purchase.condicionesPago}</p></section>}{purchase.observaciones && <section><strong>Observaciones</strong><p>{purchase.observaciones}</p></section>}</article>;
}
